NumPy stands for "Numerical Python" and is one of the most useful scientific libraries in Python programming. It provides support for large multidimensional array objects and various tools to work with them. 

An array of one dimension is called a "Vector" while having two dimensions is called a "Matrix".

NumPy arrays are called ndarray or N-dimensional arrays and they store elements of the same type and size. It is known for its high-performance and provides efficient storage and data operations as arrays grow in size.

NumPy comes pre-installed when you download Anaconda. But if you want to install NumPy separately on your machine, just type the below command on your terminal:

"pip install numpy"

Now you need to import the library:

In [74]:
import numpy as np

np is the de facto abbreviation for NumPy used by the data science community.

Python Lists vs NumPy Arrays – What’s the Difference?
------------------------------------------------------------------------------

Python lists are essentially an array of pointers, each pointing to a location that contains the information related to the element. This adds a lot of overhead in terms of memory and computation.

To overcome this problem, we use NumPy arrays that contain only homogeneous elements, i.e. elements having the same data type. This makes it more efficient at storing and manipulating the array.

1.Creating a NumPy Array
------------------------------------

In [75]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [76]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

Since NumPy arrays can contain only homogeneous datatypes, values will be upcast if the types do not match:

In [77]:
np.array([1,2.0,3,4])

array([1., 2., 3., 4.])

NumPy arrays can be multi-dimensional too.

In [78]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Array of zeros
--------------

In [79]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [80]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Array of ones
-------------------

In [81]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [82]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Random numbers in ndarrays
------------------------------------------

In [83]:
np.random.rand(2,3)

array([[0.04706173, 0.08078551, 0.86037193],
       [0.48712283, 0.89834741, 0.0384338 ]])

An array of your choice
---------------------------------

In [84]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

Imatrix in NumPy(Identity Matrix)
-----------------------------------------------

In [85]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Evenly spaced ndarray
--------------------------------

In [86]:
np.arange(5)

array([0, 1, 2, 3, 4])

The start, end and step size of the interval of values can be explicitly defined by passing in three numbers as arguments for these values respectively.

In [87]:
np.arange(2,10,2)

array([2, 4, 6, 8])

Another similar function is np.linspace(), but instead of step size, it takes in the number of samples that need to be retrieved from the interval.

In [88]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

2.Shape and Reshaping of NumPy Arrays
-----------------------------------------------------------

The shape is an attribute of the NumPy array that shows how many rows of elements are there along each dimension. 

In [89]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

You can determine how many values there are in the array using the size attribute.

In [90]:
a.size

6

Reshaping a ndarray changes the shape of the ndarray without changing the data within the ndarray:

In [91]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

Flattening a NumPy array
------------------------------------
Sometimes when you have a multidimensional array and want to collapse it to a single-dimensional array, you can either use the flatten() method or the ravel() method:

In [92]:
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()

In [93]:
b

array([1., 1., 1., 1.])

In [94]:
c

array([1., 1., 1., 1.])

3.Indexing and Slicing of NumPy array
-------------------------------------------------------

Slicing 1-D NumPy arrays
Slicing means retrieving elements from one index to another index. All we have to do is to pass the starting and ending point in the index like this: [start: end].

In [95]:
a = np.array([1,2,3,4,5,6])
print(a[1:5])

[2 3 4 5]


Incorporating all this into a single index would look something like this: [start:end:step-size].

In [96]:
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])

[2 4]


If you don’t specify the start or end index, it is taken as 0 or array size, respectively, as default. And the step-size by default is 1.

In [97]:
print(a[:6:2])

[1 3 5]


In [98]:
print(a[1::2])

[2 4 6]


In [99]:
print(a[1:6:])

[2 3 4 5 6]


Slicing 2-D arrays

In [100]:
a = np.array([[1,2,3],[4,5,6]])
print('Arbitrary values :','\n',a[0:2,1:3])

Arbitrary values : 
 [[2 3]
 [5 6]]


Negative slicing of NumPy arrays

In [101]:
print(a[:,-1:-3:-1])

[[3 2]
 [6 5]]


4.Appending Numpy Arrays
----------------------

Another very useful function is the "append" method that adds new elements to the end of a ndarray. This is obviously useful when you already have an existing ndarray but want to add new values to it.

In [102]:
a = np.array([[1,2],
             [3,4]])
np.append(a,[[5,6]],axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

5.Broadcasting in NumPy array
---------------------------
Broadcasting is one of the best features of ndarrays. It lets you perform arithmetics operations between ndarrays of different sizes or between an ndarray and a simple number!

In [103]:
a = np.arange(10,20,2)
b = np.array([[2],[2]])
print(a+b)
print()
print(a*2)

[[12 14 16 18 20]
 [12 14 16 18 20]]

[20 24 28 32 36]


Basic arithmetic operations

In [104]:
print(a-5)
print(a*5)
print(a/5)
print(a**2)
print(a%5)

[ 5  7  9 11 13]
[50 60 70 80 90]
[2.  2.4 2.8 3.2 3.6]
[100 144 196 256 324]
[0 2 4 1 3]


Mean, Median and Standard deviation

In [105]:
a = np.arange(5,15,2)
print("Mean : ", np.mean(a))
print("Standard Deviation :",np.std(a))
print("Median :",np.median(a))

Mean :  9.0
Standard Deviation : 2.8284271247461903
Median : 9.0


Min-Max values and their indexes

In [106]:
print('Min :',np.min(a))
print('Index of Min :',np.argmin(a))

print('Max :',np.max(a))
print('Index of Max :',np.argmax(a))

Min : 5
Index of Min : 0
Max : 13
Index of Max : 4


In [107]:
a=np.array([9, 2, 8, 4, 7, 3, 1, 6, 5])
a

array([9, 2, 8, 4, 7, 3, 1, 6, 5])

6.Sorting in NumPy arrays
--------------------------------

In [108]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])